export enum ServiceTypeEnum {
  ROUTER = 'ROUTER',
  VALIDATORS_API = 'VALIDATORS_API',
  PROPOSAL_API = 'PROPOSAL_API',
  ACCOUNT_API = 'ACCOUNT_API',
  TOKENS_API = 'TOKENS_API',
  BLOCK_API = 'BLOCK_API',
  WALLET_API = 'WALLET_API',
  USER_STORE = 'USER_STORE',
  VALIDATORS_STORE = 'VALIDATORS_STORE',
  TOKENS_STORE = 'TOKENS_STORE',
}
