export enum ServiceTypeEnum {
  ROUTER = 'ROUTER',
  VALIDATORS_SERVICE = 'VALIDATORS_SERVICE',
  POOLS_SERVICE = 'POOLS_SERVICE',
  LATEST_BLOCK_SERVICE = 'LATEST_BLOCK_SERVICE',
  TOTAL_SUPPLY_SERVICE = 'TOTAL_SUPPLY_SERVICE',
  TOKENOMICS_SERVICE = 'TOKENOMICS_SERVICE',
  ACTIVE_VALIDATORS_SERVICE = 'ACTIVE_VALIDATORS_SERVICE',
  AVERAGE_BLOCK_TIME = 'AVERAGE_BLOCK_TIME',
  PROPOSAL_SERVICE = 'PROPOSAL_SERVICE',
  TALLYING_SERVICE = 'TALLYING_SERVICE',
  ACCOUNT_SERVICE = 'ACCOUNT_SERVICE',
}
