export enum RoleEnum{
  SUPER_ADMIN= 'SUPER_ADMIN',
  ADMINISTRATOR_FULL= 'ADMINISTRATOR_FULL',
  ADMINISTRATOR_BASIC= 'ADMINISTRATOR_BASIC',
  TRADER= 'TRADER',
  SUPER_AGENT= 'SUPER_AGENT',
  AGENT= 'AGENT',
  PROSUMER= 'PROSUMER'
}
